// Auto-generated by Wails. Do not edit manually.
// This file will be replaced by `wails dev` / `wails build`.

export function EventsOn(eventName: string, callback: (...data: unknown[]) => void): () => void;
export function EventsOff(eventName: string, ...additionalEventNames: string[]): void;
export function EventsOnce(eventName: string, callback: (...data: unknown[]) => void): void;
export function EventsEmit(eventName: string, ...data: unknown[]): void;

export function LogPrint(message: string): void;
export function LogTrace(message: string): void;
export function LogDebug(message: string): void;
export function LogInfo(message: string): void;
export function LogWarning(message: string): void;
export function LogError(message: string): void;
export function LogFatal(message: string): void;

export function WindowReload(): void;
export function WindowReloadApp(): void;
export function WindowSetSystemDefaultTheme(): void;
export function WindowSetLightTheme(): void;
export function WindowSetDarkTheme(): void;
export function WindowCenter(): void;
export function WindowSetTitle(title: string): void;
export function WindowFullscreen(): void;
export function WindowUnfullscreen(): void;
export function WindowSetSize(width: number, height: number): void;
export function WindowGetSize(): Promise<{ w: number; h: number }>;
export function WindowSetMinSize(width: number, height: number): void;
export function WindowSetMaxSize(width: number, height: number): void;
export function WindowSetAlwaysOnTop(b: boolean): void;
export function WindowSetPosition(x: number, y: number): void;
export function WindowGetPosition(): Promise<{ x: number; y: number }>;
export function WindowMaximise(): void;
export function WindowToggleMaximise(): void;
export function WindowUnmaximise(): void;
export function WindowMinimise(): void;
export function WindowUnminimise(): void;
export function WindowShow(): void;
export function WindowHide(): void;
export function WindowIsMaximised(): Promise<boolean>;
export function WindowIsMinimised(): Promise<boolean>;
export function WindowIsNormal(): Promise<boolean>;
export function WindowIsFullscreen(): Promise<boolean>;
export function WindowSetBackgroundColour(R: number, G: number, B: number, A: number): void;

export function Quit(): void;
export function Hide(): void;
export function Show(): void;

export function BrowserOpenURL(url: string): void;

export function Environment(): Promise<{ buildType: string; platform: string; arch: string }>;
export function IsFullscreen(): Promise<boolean>;
export function IsMaximised(): Promise<boolean>;
export function IsMinimised(): Promise<boolean>;
export function IsNormal(): Promise<boolean>;

export type GoEvent = unknown;
