// Auto-generated by Wails. Do not edit manually.
// This file will be replaced by `wails dev` / `wails build`.

export interface PortMapping {
  id: string;
  listenPort: number;
  wslPort: number;
}

export interface WSLInfo {
  ip: string;
  mode: string;
  targetIP: string;
}

export function GetWSLInfo(): Promise<WSLInfo | null>;
export function GetMappings(): Promise<PortMapping[]>;
export function GetState(): Promise<string>;
export function AddMapping(spec: string): Promise<void>;
export function RemoveMapping(id: string): Promise<void>;
export function Start(): Promise<void>;
export function Pause(): Promise<void>;
export function Stop(): Promise<void>;
export function ClearLog(): Promise<void>;
